/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { LabService } from "../lab.service";
import { LabCreateInput } from "./LabCreateInput";
import { Lab } from "./Lab";
import { LabFindManyArgs } from "./LabFindManyArgs";
import { LabWhereUniqueInput } from "./LabWhereUniqueInput";
import { LabUpdateInput } from "./LabUpdateInput";
import { EmployeeFindManyArgs } from "../../employee/base/EmployeeFindManyArgs";
import { Employee } from "../../employee/base/Employee";
import { EmployeeWhereUniqueInput } from "../../employee/base/EmployeeWhereUniqueInput";
import { TraineeFindManyArgs } from "../../trainee/base/TraineeFindManyArgs";
import { Trainee } from "../../trainee/base/Trainee";
import { TraineeWhereUniqueInput } from "../../trainee/base/TraineeWhereUniqueInput";

export class LabControllerBase {
  constructor(protected readonly service: LabService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Lab })
  async createLab(@common.Body() data: LabCreateInput): Promise<Lab> {
    return await this.service.createLab({
      data: data,
      select: {
        address: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Lab] })
  @ApiNestedQuery(LabFindManyArgs)
  async labs(@common.Req() request: Request): Promise<Lab[]> {
    const args = plainToClass(LabFindManyArgs, request.query);
    return this.service.labs({
      ...args,
      select: {
        address: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Lab })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async lab(@common.Param() params: LabWhereUniqueInput): Promise<Lab | null> {
    const result = await this.service.lab({
      where: params,
      select: {
        address: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Lab })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateLab(
    @common.Param() params: LabWhereUniqueInput,
    @common.Body() data: LabUpdateInput
  ): Promise<Lab | null> {
    try {
      return await this.service.updateLab({
        where: params,
        data: data,
        select: {
          address: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Lab })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteLab(
    @common.Param() params: LabWhereUniqueInput
  ): Promise<Lab | null> {
    try {
      return await this.service.deleteLab({
        where: params,
        select: {
          address: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/employees")
  @ApiNestedQuery(EmployeeFindManyArgs)
  async findEmployees(
    @common.Req() request: Request,
    @common.Param() params: LabWhereUniqueInput
  ): Promise<Employee[]> {
    const query = plainToClass(EmployeeFindManyArgs, request.query);
    const results = await this.service.findEmployees(params.id, {
      ...query,
      select: {
        createdAt: true,
        dateOfJoining: true,
        email: true,
        firstName: true,
        id: true,

        lab: {
          select: {
            id: true,
          },
        },

        lastName: true,
        phoneNumber: true,

        role: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/employees")
  async connectEmployees(
    @common.Param() params: LabWhereUniqueInput,
    @common.Body() body: EmployeeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      employees: {
        connect: body,
      },
    };
    await this.service.updateLab({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/employees")
  async updateEmployees(
    @common.Param() params: LabWhereUniqueInput,
    @common.Body() body: EmployeeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      employees: {
        set: body,
      },
    };
    await this.service.updateLab({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/employees")
  async disconnectEmployees(
    @common.Param() params: LabWhereUniqueInput,
    @common.Body() body: EmployeeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      employees: {
        disconnect: body,
      },
    };
    await this.service.updateLab({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/trainees")
  @ApiNestedQuery(TraineeFindManyArgs)
  async findTrainees(
    @common.Req() request: Request,
    @common.Param() params: LabWhereUniqueInput
  ): Promise<Trainee[]> {
    const query = plainToClass(TraineeFindManyArgs, request.query);
    const results = await this.service.findTrainees(params.id, {
      ...query,
      select: {
        createdAt: true,
        dateOfJoining: true,
        email: true,
        firstName: true,
        id: true,

        lab: {
          select: {
            id: true,
          },
        },

        lastName: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/trainees")
  async connectTrainees(
    @common.Param() params: LabWhereUniqueInput,
    @common.Body() body: TraineeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trainees: {
        connect: body,
      },
    };
    await this.service.updateLab({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/trainees")
  async updateTrainees(
    @common.Param() params: LabWhereUniqueInput,
    @common.Body() body: TraineeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trainees: {
        set: body,
      },
    };
    await this.service.updateLab({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/trainees")
  async disconnectTrainees(
    @common.Param() params: LabWhereUniqueInput,
    @common.Body() body: TraineeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trainees: {
        disconnect: body,
      },
    };
    await this.service.updateLab({
      where: params,
      data,
      select: { id: true },
    });
  }
}
